spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gosselin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/base_donnees/base.xml